### ISSUE TITLE
Проблема при запуске

### ISSUE THREAD

**Issue by Danila-Kovalenko** [Xewus/Foodgram#21]
Слушай, а как теги подгрузить, а то в гитхаб версии, если скопировать на виртуальный сервер, тегов не будет?

**Comment by Xewus** [comment]
В описании указано, что в дампе БД только ингредиенты.
Набор ингредиентов, как и фронтенд, предоставлены командой Яндекса.
Здесь немного поправленные, так как две буквы в их наборе были не в нижнем регистре.

Теги создаются вручную, на запущенном сервере.

В принципе, пару тегов можно и вручную в дамп дописать.

**Comment by Xewus** [comment]
Тэги "завтрак", "обед", "ужин" добавлены в дамп.
