### ISSUE TITLE
Request for project database models

### ISSUE THREAD

**Issue by mavhungutrezzy** [Xewus/Foodgram#24]
I hope you're doing well. I am interested in using your project's database model in my own project, which is built in FastAPI. However, since your project is built in Django, I'm not sure how to go about creating the database schema for my own project.

I was wondering if you could provide me with the database model for your project. This would be a great help to me as it would save me time and effort in building my own schema.

**Comment by Xewus** [comment]
![db_scheme](https://user-images.githubusercontent.com/85196001/225128432-99b8b1ce-37c7-46da-905b-8c9297e0bb9e.png)

In fact, Django adds 17 more tables to store sessions, migrations, authentications, etc.
And Django adds an id field to every table. This is not needed in M2M tables. You can use FK+FK as the primary key.

**Comment by mavhungutrezzy** [comment]
Thank you
