### ISSUE TITLE
Баг с рецептом (редактирование)

### ISSUE THREAD

**Issue by QA-Denis** [Xewus/Foodgram#26]
Если, после создания рецепта с нескольким ингредиентом, редактировать рецепт - добавить ингредиент, то после сохранения кол-во(amount) конкретных ингредиентов изменятся.

**Comment by Xewus** [comment]
Подтверждено.
Ситуация оказалась даже ещё хуже.

**Comment by Xewus** [comment]
Пофикшено, по крайней мере на тех данных, что некорректно срабатывали у меня.

Также возникала ошибка, когда пользователь писал "соль 20 г", а затем добавлял "соль 30 г".
Теперь значения складываются в "соль 50 г".
По желанию, немного подстроив строку `176` в `../bacend/core/validators/`, можно сохранять только одно значение.

Попутно оптимизирован запрос в БД при валидации ингредиентов.
