### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by IvanMironov1246** [Xewus/Foodgram#29]
Использую python 3.7
при миграции выдает такую ошибку в core\validators.py. Подскажи, пожалуйста, как исправить?

**Comment by Xewus** [comment]
Эта ошибка не относится к самим миграциям, интерпретатор ломается при чтении кода.

Ошибка связана с аннотацией типов. Здесь использован новый синтаксис для этого. Например:
```
def foo(a: int | None = None) -> None:
    return
```
Означает, что функция `foo` ожидает входящий аргумент типа `целое число` или (` | `) `None`, но аргумент передавать не обязательно и если аргумент не будет передан, то будет использовано значение по умолчанию `None`.
Данный синтаксис с оператором " | " поддерживается версиями Python 3.10 и выше.

Варианты обхода ошибки:
- Использовать Python 3.10 или выше.
- Изменить в коде на старый вариант аннотирования, то есть для случая указанного в примере придётся написать так:
```
from typing import Optional

def foo(a: Optional[int] = None) -> None:
    return
```
- Вовсе удалить аннотации, так как в данном проекте они не имеют значения.


Также все зависимости следует устанавливать в соответствии с файлом `requirements.txt`, иначе, даже если программа запустится, иногда будут возникать ошибки из-за разных версий библиотек, ввиду переименования или удаления каких-то функций.

**Comment by IvanMironov1246** [comment]
Спасибо!
